# Configuration for ExoplanetDetection Pipeline

adaboost:
  iterations: 1000
  learning_rate: 0.1
  depth: 6
  early_stopping_rounds: 50
  task_type: CPU  # Change to GPU if available

ensemble_strategy: weighted  # Options: voting, weighted, stacking

pretrained_model_path: null  # Path to pretrained model if available