# Configuration for ExoplanetDetection Pipeline

adaboost:
  iterations: 1000
  learning_rate: 0.1
  depth: 6
  early_stopping_rounds: 50
  task_type: CPU  # Change to GPU if available

rand_forest:
  n_estimators: 900            # number of trees
  criterion: gini              # or "entropy"
  max_depth: null              # let trees grow; control with min_samples_leaf
  min_samples_split: 2
  min_samples_leaf: 2          # try 1–4 to reduce variance
  max_features: sqrt           # decorrelates trees; can try 0.5 too
  bootstrap: true
  oob_score: false             # true = get out-of-bag validation score
  class_weight: balanced       # helps if confirmed planets are rarer
  n_jobs: -1                   # use all CPU cores
  random_state: 42

ensemble_strategy: voting  # Options: voting, weighted, stacking

pretrained_model_path: null  # Path to pretrained model if available